/// Flutter icons BREIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BREIcons
///      fonts:
///       - asset: fonts/BREIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BREIcons {
  BREIcons._();

  static const _kFontFam = 'BREIcons';
  static const String? _kFontPkg = null;

  static const IconData home_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData client_profile_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
